/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rohit Kumar
 */


import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.List;
import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.swingx.JXMapViewer;
import org.jdesktop.swingx.mapviewer.GeoPosition;
import org.jdesktop.swingx.mapviewer.TileFactory;
import org.jdesktop.swingx.mapviewer.Waypoint;
import org.jdesktop.swingx.mapviewer.WaypointPainter;
import org.jdesktop.swingx.mapviewer.WaypointRenderer;
import org.jdesktop.swingx.painter.Painter;
import java.lang.String;

public class BrandSelection extends javax.swing.JFrame {

    /**
     * Creates new form BrandSelection
     */
    public BrandSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAlertDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jAlertButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBrandCombo1 = new javax.swing.JComboBox();
        jBrandCombo2 = new javax.swing.JComboBox();
        jVillanova = new javax.swing.JButton();
        jImportButton = new javax.swing.JButton();
        jCompare = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jValueLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jXMapKit1 = new org.jdesktop.swingx.JXMapKit();

        jAlertDialog.setTitle("Alert!!");

        jLabel6.setText("Please Select 2 Different Brands");

        jAlertButton.setText("OK");
        jAlertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jAlertButton)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jAlertButton)
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout jAlertDialogLayout = new javax.swing.GroupLayout(jAlertDialog.getContentPane());
        jAlertDialog.getContentPane().setLayout(jAlertDialogLayout);
        jAlertDialogLayout.setHorizontalGroup(
            jAlertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAlertDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jAlertDialogLayout.setVerticalGroup(
            jAlertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAlertDialogLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("     Brand Gravity Analyzer");

        jLabel2.setText("Select Brand 1:");

        jLabel3.setText("Select Brand 2:");

        jBrandCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrandCombo1ActionPerformed(evt);
            }
        });

        jVillanova.setText("goVillanova");
        jVillanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVillanovaActionPerformed(evt);
            }
        });

        jImportButton.setText("Import Brands");
        jImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImportButtonActionPerformed(evt);
            }
        });

        jCompare.setText("Compare");
        jCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBrandCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBrandCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jCompare)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jImportButton)
                            .addComponent(jVillanova, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jCompare))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jBrandCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jImportButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBrandCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jVillanova))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel4.setText("Correlations:");

        jLabel5.setText("Value:");

        jValueLabel.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(49, 49, 49)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jXMapKit1.setDefaultProvider(org.jdesktop.swingx.JXMapKit.DefaultProviders.OpenStreetMaps);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXMapKit1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXMapKit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAlertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlertButtonActionPerformed
        // TODO add your handling code here:
        jAlertDialog.dispose();
    }//GEN-LAST:event_jAlertButtonActionPerformed

    private void jBrandCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrandCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBrandCombo1ActionPerformed

    private void jVillanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVillanovaActionPerformed
        // TODO add your handling code here:
        //jXMapKit1.setAddressLocation(new GeoPosition(41.881944,-87.627778));
        jXMapKit1.setAddressLocation(new  GeoPosition(40.0377,-75.3376));
        jXMapKit1.setBackground(Color.red);
       
        jXMapKit1.getCenterPosition();
    }//GEN-LAST:event_jVillanovaActionPerformed

    private void jImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImportButtonActionPerformed
        try {
            // TODO add your handling code here:
          
            Scanner myscanner = new Scanner(new File("Brand.txt"));
           // for(int i=0;i<4;i++)
            //Adding brands to the combo boxes from the Brand.txt file
            String brand;
            while(myscanner.hasNextLine())
            {
                brand=myscanner.nextLine();
                jBrandCombo1.addItem(brand);
                jBrandCombo2.addItem(brand);
            }
            //myscanner.nextLine();
    /*for(int i=1;i<=3;i++){
     *
            myscanner
    }*/ } catch (FileNotFoundException ex) {
            Logger.getLogger(BrandSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
    	
    }//GEN-LAST:event_jImportButtonActionPerformed

    private void jCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompareActionPerformed
                
            // TODO add your handling code here:
        jValueLabel.setEnabled(true);
        if(jBrandCombo1.getSelectedIndex()== jBrandCombo2.getSelectedIndex()){
            jAlertDialog.setVisible(true);
            System.out.println("Please Select 2 different brands");
        }
        else{
            Set<Waypoint> waypoints = new HashSet<Waypoint>();     
            String selection1=(String) jBrandCombo1.getSelectedItem();
            String selection2=(String) jBrandCombo2.getSelectedItem();
            try{
                Scanner scanner = new Scanner(new File("Locations.txt"));
                //Set the delimiter used in file
                scanner.useDelimiter(",");
                //Get all tokens and store them in some data structure
                //I am just printing them
                while (scanner.hasNext()) 
                {
                    String Brand= scanner.next();        
                    String latitude= scanner.next();
                  //  System.out.println(latitude+" latitude | ");
                    String longitude = scanner.next();
                //    System.out.println(longitude+" longi | ");
                    scanner.nextLine();
                    if(Brand.equalsIgnoreCase(selection1)||Brand.equalsIgnoreCase(selection2)){
                        double lat= Double.parseDouble(latitude);
                        double long1= Double.parseDouble(longitude);
                        waypoints.add(new Waypoint(lat,-long1));                 
                    }              
                }      
                scanner.close();
                WaypointPainter painter;
                painter = new WaypointPainter();
                painter.setWaypoints(waypoints);              
                jXMapKit1.getMainMap().setOverlayPainter(painter);
                jXMapKit1.setBackground(Color.red);                            
           }
            catch (FileNotFoundException ex) {
                Logger.getLogger(BrandSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*  Set<Waypoint> waypoints = new HashSet<Waypoint>();
         
             
           // Set waypoints = new HashSet();
          //waypoints.add(new Waypoint(41.881944,-87.627778)); sample points
   // waypoints.add(new Waypoint(40.716667,-74));
           // jXMapKit1.setAddressLocation(new  GeoPosition(40.716667,-74));
            //for(int i=0;i<4;i++){
            
           
            waypoints.add(new Waypoint(40.716667,-74));
             waypoints.add(new Waypoint(41.881944,-87.627778));
            waypoints.add(new Waypoint(40.026024,-75.327585));
            waypoints.add(new Waypoint(40.067816,-75.311350));
            waypoints.add(new Waypoint(40.029364,-75.333029));
            waypoints.add(new Waypoint(40.043484,-75.378427));
            WaypointPainter painter;
            painter = new WaypointPainter();
            painter.setWaypoints(waypoints);
              
              jXMapKit1.getMainMap().setOverlayPainter(painter);
              jXMapKit1.setBackground(Color.red);
              // this.jXMapKit1.getMainMap().setOverlayPainter(painter);
             /*  painter.setRenderer(new WaypointRenderer()
             {
              public boolean paintWaypoint(Graphics2D g, JXMapViewer map, Waypoint wp) 
               {
                    g.setColor(Color.RED);
                    g.drawLine(-5,-5,+5,+5);
                    g.drawLine(-5,+5,+5,-5);
                    return true;
                }
     
             }); */
         //  jXMapKit1.getMainMap().setOverlayPainter(painter);
           //jXMapKit1.getMiniMap().setOverlayPainter(painter);
        }
        String combo1=(String)jBrandCombo1.getSelectedItem();
        String combo2=(String)jBrandCombo2.getSelectedItem();
        try{
                Scanner scanner = new Scanner(new File("Corelation.txt"));
                //Set the delimiter used in file
                scanner.useDelimiter(",");
                //Get all tokens and store them in some data structure
                //I am just printing them
                while (scanner.hasNext()) 
                {
                    String brand1= scanner.next();        
                   // System.out.println(brand1+" brand1 ");
                    String brand2= scanner.next();
                   // System.out.println(brand2+" brand2 ");
                    String val = scanner.next();
                   // System.out.println(val+" val ");
                    
                    scanner.nextLine();
                    
                    if(brand1.equalsIgnoreCase(combo1) && brand2.equalsIgnoreCase(combo2))
                    {
                         jValueLabel.setEnabled(true);
                        jValueLabel.setText(val);
                       
                    }
                    
                }      
                scanner.close();                         
           }
            catch (FileNotFoundException ex) {
                Logger.getLogger(BrandSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCompareActionPerformed
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrandSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrandSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrandSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrandSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrandSelection().setVisible(true);
            }
        });
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAlertButton;
    private javax.swing.JDialog jAlertDialog;
    private javax.swing.JComboBox jBrandCombo1;
    private javax.swing.JComboBox jBrandCombo2;
    private javax.swing.JButton jCompare;
    private javax.swing.JButton jImportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jValueLabel;
    private javax.swing.JButton jVillanova;
    private org.jdesktop.swingx.JXMapKit jXMapKit1;
    // End of variables declaration//GEN-END:variables
}
